"""update auth saved and recent location models

Revision ID: 038ab44c2ffa
Revises: 4a84a37590bd
Create Date: 2026-06-10 00:30:12.361740

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '038ab44c2ffa'
down_revision: Union[str, Sequence[str], None] = '4a84a37590bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recent_locations',
    sa.Column('recent_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('location_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('recent_id'),
    sa.UniqueConstraint('user_id', 'location_id', name='unique_recent')
    )
    op.add_column('map_edges',sa.Column('is_sheltered', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('map_edges',sa.Column('is_accessible', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.alter_column('map_edges', 'distance_m',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    op.create_unique_constraint('unique_save', 'saved_locations', ['user_id', 'location_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_save', 'saved_locations', type_='unique')
    op.alter_column('map_edges', 'distance_m',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    op.drop_column('map_edges', 'is_accessible')
    op.drop_column('map_edges', 'is_sheltered')
    op.drop_table('recent_locations')
    # ### end Alembic commands ###
