"""create locations table

Revision ID: 04535507d59f
Revises: 
Create Date: 2026-05-27 18:29:10.620370

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '04535507d59f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('aliases', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('location_type', sa.String(), nullable=False),
    sa.Column('building_code', sa.String(), nullable=True),
    sa.Column('building_name', sa.String(), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=True),
    sa.Column('available_floors', postgresql.ARRAY(sa.Integer()), nullable=False),
    sa.Column('area_name', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longtitude', sa.Float(), nullable=True),
    sa.Column('nearest_node_id', sa.String(), nullable=True),
    sa.Column('nearest_bus_stop_id', sa.String(), nullable=True),
    sa.Column('landmark_hint', sa.String(), nullable=True),
    sa.Column('arrival_instruction', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('locations')
    # ### end Alembic commands ###
