"""add canteens, boundaries, crowd_density, opening_hours

Revision ID: 0db720acc984
Revises: 7fee68dd0e3f
Create Date: 2026-06-21 00:10:25.064462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0db720acc984'
down_revision: Union[str, Sequence[str], None] = '7fee68dd0e3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('canteens',
    sa.Column('location_id', sa.String(), nullable=False),
    sa.Column('halal_availability', sa.Boolean(), nullable=False),
    sa.Column('stalls', postgresql.ARRAY(sa.String()), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('location_id')
    )
    op.add_column('buildings', sa.Column('boundaries', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('locations', sa.Column('boundaries', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('locations', sa.Column('crowd_density', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('locations', sa.Column('opening_hours', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'opening_hours')
    op.drop_column('locations', 'crowd_density')
    op.drop_column('locations', 'boundaries')
    op.drop_column('buildings', 'boundaries')
    op.drop_table('canteens')
    # ### end Alembic commands ###
