"""add unique constraint to saved locations

Revision ID: 1667365fdb4b
Revises: f3a6cdad586b
Create Date: 2026-05-30 17:24:00.184623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1667365fdb4b'
down_revision: Union[str, Sequence[str], None] = 'f3a6cdad586b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
