"""set up bus service model

Revision ID: 1f5cd0d4447f
Revises: 5b2e5aee33cf
Create Date: 2026-06-22 00:59:28.019148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f5cd0d4447f'
down_revision: Union[str, Sequence[str], None] = '5b2e5aee33cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buses',
    sa.Column('bus_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bus_number', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('bus_id'),
    sa.UniqueConstraint('bus_number')
    )
    op.create_table('bus_stops',
    sa.Column('bus_stop_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('node_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['node_id'], ['map_nodes.node_id'], ),
    sa.PrimaryKeyConstraint('bus_stop_id')
    )
    op.create_table('bus_stop_schedules',
    sa.Column('bus_id', sa.Integer(), nullable=False),
    sa.Column('bus_stop_id', sa.String(), nullable=False),
    sa.Column('schedule', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['bus_id'], ['buses.bus_id'], ),
    sa.ForeignKeyConstraint(['bus_stop_id'], ['bus_stops.bus_stop_id'], ),
    sa.PrimaryKeyConstraint('bus_id', 'bus_stop_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bus_stop_schedules')
    op.drop_table('bus_stops')
    op.drop_table('buses')
    # ### end Alembic commands ###
