"""users: add pace_factor, shelter_pref; drop profile_settings

Revision ID: 23c0632b0d49
Revises: 15e1052461c8
Create Date: 2026-07-12 00:21:46.757726

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '23c0632b0d49'
down_revision: Union[str, Sequence[str], None] = '15e1052461c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pace_factor', sa.Float(), nullable=False))
    op.add_column('users', sa.Column('shelter_pref', sa.Float(), nullable=False))
    op.drop_column('users', 'profile_settings')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('profile_settings', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('users', 'shelter_pref')
    op.drop_column('users', 'pace_factor')
    # ### end Alembic commands ###
