"""add affine column to floors

Revision ID: 28f96da26079
Revises: 1f5cd0d4447f
Create Date: 2026-06-22 17:31:08.011807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '28f96da26079'
down_revision: Union[str, Sequence[str], None] = '1f5cd0d4447f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('floors', sa.Column('affine', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('floors', 'affine')
    # ### end Alembic commands ###
