"""building entrance_node_id nullable fk

Revision ID: 5b2e5aee33cf
Revises: 0db720acc984
Create Date: 2026-06-21 01:20:42.941037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b2e5aee33cf'
down_revision: Union[str, Sequence[str], None] = '0db720acc984'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('buildings', sa.Column('entrance_node_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'buildings', 'map_nodes', ['entrance_node_id'], ['node_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'buildings', type_='foreignkey')
    op.drop_column('buildings', 'entrance_node_id')
    # ### end Alembic commands ###
