"""map_edges: vertical

Revision ID: 684307605333
Revises: 23c0632b0d49
Create Date: 2026-07-16 12:59:02.336531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '684307605333'
down_revision: Union[str, Sequence[str], None] = '23c0632b0d49'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('map_edges', sa.Column('vertical', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('map_edges', 'vertical')
    # ### end Alembic commands ###
