"""add buildings and floors tables

Revision ID: 7fee68dd0e3f
Revises: 038ab44c2ffa
Create Date: 2026-06-16 23:42:03.239394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7fee68dd0e3f'
down_revision: Union[str, Sequence[str], None] = '038ab44c2ffa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buildings',
    sa.Column('building_id', sa.String(), nullable=False),
    sa.Column('building_code', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('aliases', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('area_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('building_id')
    )
    op.create_table('floors',
    sa.Column('floor_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('floor_number', sa.Integer(), nullable=False),
    sa.Column('floor_name', sa.String(), nullable=False),
    sa.Column('building_id', sa.String(), nullable=False),
    sa.Column('geo_reference', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('image_url', sa.String(), nullable=False),
    sa.Column('image_width', sa.Integer(), nullable=False),
    sa.Column('image_height', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['building_id'], ['buildings.building_id'], ),
    sa.PrimaryKeyConstraint('floor_id'),
    sa.UniqueConstraint('floor_number', 'building_id', name='unique_floor')
    )
    op.add_column('locations', sa.Column('building_id', sa.String(), nullable=True))
    op.add_column('locations', sa.Column('floor_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'locations', 'floors', ['floor_id'], ['floor_id'])
    op.create_foreign_key(None, 'locations', 'buildings', ['building_id'], ['building_id'])
    op.drop_column('locations', 'floor')
    op.drop_column('locations', 'building_code')
    op.drop_column('locations', 'building_name')
    op.drop_column('locations', 'available_floors')
    op.alter_column('map_nodes', 'building_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.execute("UPDATE map_nodes SET building_id = NULL")
    op.create_foreign_key(None, 'map_nodes', 'buildings', ['building_id'], ['building_id'])
    op.drop_column('map_nodes', 'building_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('map_nodes', sa.Column('building_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'map_nodes', type_='foreignkey')
    op.alter_column('map_nodes', 'building_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('locations', sa.Column('available_floors', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=False))
    op.add_column('locations', sa.Column('building_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('locations', sa.Column('building_code', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('locations', sa.Column('floor', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'locations', type_='foreignkey')
    op.drop_constraint(None, 'locations', type_='foreignkey')
    op.drop_column('locations', 'floor_id')
    op.drop_column('locations', 'building_id')
    op.drop_table('floors')
    op.drop_table('buildings')
    # ### end Alembic commands ###
