"""buildings model added display coords

Revision ID: c116107775c3
Revises: 684307605333
Create Date: 2026-07-19 01:18:33.566887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c116107775c3'
down_revision: Union[str, Sequence[str], None] = '684307605333'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add as nullable first so the ALTER doesn't fail on existing rows, backfill
    # each building's display coords, then enforce NOT NULL to match the model.
    op.add_column('buildings', sa.Column('display_latitude', sa.Float(), nullable=True))
    op.add_column('buildings', sa.Column('display_longitude', sa.Float(), nullable=True))

    building_coords = {
        'com1': (1.2952525534852652, 103.77376451115138),
        'com2': (1.2943070185269383, 103.77410604722144),
        'com3': (1.294759386948188, 103.77457751952595),
        'com4': (1.2951652964409013, 103.77540756232389),
        'as6': (1.295738285690793, 103.77318108795896),
        'src': (1.3045009737282307, 103.77245117864669),
    }
    buildings = sa.table(
        'buildings',
        sa.column('building_id', sa.String),
        sa.column('display_latitude', sa.Float),
        sa.column('display_longitude', sa.Float),
    )
    for building_id, (lat, lon) in building_coords.items():
        op.execute(
            buildings.update()
            .where(buildings.c.building_id == building_id)
            .values(display_latitude=lat, display_longitude=lon)
        )

    op.alter_column('buildings', 'display_latitude', existing_type=sa.Float(), nullable=False)
    op.alter_column('buildings', 'display_longitude', existing_type=sa.Float(), nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('buildings', 'display_longitude')
    op.drop_column('buildings', 'display_latitude')
    # ### end Alembic commands ###
