"""update to match versions

Revision ID: d427e9acfb6c
Revises: 06afdf806945
Create Date: 2026-05-31 00:04:15.466849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd427e9acfb6c'
down_revision: Union[str, Sequence[str], None] = '1667365fdb4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('map_nodes',
    sa.Column('node_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('node_type', sa.String(), nullable=False),
    sa.Column('building_id', sa.String(), nullable=False),
    sa.Column('building_code', sa.String(), nullable=True),
    sa.Column('floor', sa.Integer(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('node_id')
    )
    op.create_table('map_edges',
    sa.Column('edge_id', sa.String(), nullable=False),
    sa.Column('from_node_id', sa.String(), nullable=False),
    sa.Column('to_node_id', sa.String(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('distance_m', sa.Integer(), nullable=False),
    sa.Column('estimated_seconds', sa.Float(), nullable=False),
    sa.Column('instruction', sa.String(), nullable=True),
    sa.Column('geometry', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['from_node_id'], ['map_nodes.node_id'], ),
    sa.ForeignKeyConstraint(['to_node_id'], ['map_nodes.node_id'], ),
    sa.PrimaryKeyConstraint('edge_id')
    )
    op.add_column('locations', sa.Column('longitude', sa.Float(), nullable=True))
    op.drop_column('locations', 'longtitude')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locations', sa.Column('longtitude', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('locations', 'longitude')
    op.drop_table('map_edges')
    op.drop_table('map_nodes')
    # ### end Alembic commands ###
