"""add description to locations

Revision ID: f3a6cdad586b
Revises: 04535507d59f
Create Date: 2026-05-30 01:21:39.982850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3a6cdad586b'
down_revision: Union[str, Sequence[str], None] = '04535507d59f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "locations",
        sa.Column("description", sa.String(), nullable=False, server_default="")
    )
    op.alter_column("locations", "description", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'description')
    # ### end Alembic commands ###
