services:
  db:
    image: postgres:16
    container_name: nus-nav-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: routes@nus123
      POSTGRES_DB: nus_nav
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: